Removed unused components, removed bsd code to reduce the binary cause i am on linux

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,9 +1,26 @@
 #!/bin/env bash
-echo -e "Removing old build"
+RED='\033[0;31m'
+GRN='\033[0;32m'
+YEL='\033[0;33m'
+CYN='\033[0;36m'
+RES='\033[0m'
+
+###### Clean and build ######
+echo -e "[${CYN}MSG${RES} Removing old build${RES}"
 make clean
-echo -e "Rmoving old config.h"
-rm config.h
-echo -e "Compiling ..."
+echo -e "[${GRN}OK!${RES}] Cleaned\n"
+
+echo -e "[${CYN}MSG${RES}] Removing old config.h${RES}"
+echo -e "rm -rf config.h"
+rm -rf config.h
+echo -e "[${GRN}OK!${RES}] Cleaned\n"
+
+echo -e "[${CYN}MSG${RES}] Compiling ..."
 make
-echo -e "Type root pass to install"
-sudo make install
+if [ $? -eq 0 ]; then
+    echo -e "[${GRN}OK!${RES}] Compilation Success\n${YEL}"
+    sudo make install
+    echo -e "${RES}"
+else
+    echo -e "[${RED}ERR${RES}] Compilation ${RED}Failed!${RES}, please check errors"
+fi
